(deftheme photon
  "Created 2019-05-25.")

(custom-theme-set-faces
 'photon
 '(cursor ((t (:background "#c6c6c6"))))
 '(fixed-pitch ((t nil)))
 '(variable-pitch ((t nil)))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :box (:line-width -1 :color nil :style released-button) :foreground "#0184bc"))))
 '(highlight ((t (:background "#303030"))))
 '(region ((t (:background "#3a3a3a" :distant-foreground nil))))
 '(shadow ((t (:foreground "#626262"))))
 '(secondary-selection ((t (:background "deep sky blue"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "#c6c6c6"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "#626262"))))
 '(font-lock-constant-face ((t (:foreground "#af87d7"))))
 '(font-lock-doc-face ((t (:slant italic :inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#c6c6c6"))))
 '(font-lock-keyword-face ((t (:foreground "#767676"))))
 '(font-lock-negation-char-face ((t (:weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#767676" :inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#767676" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "black" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#af87d7"))))
 '(font-lock-type-face ((t (:foreground "#c6c6c6"))))
 '(font-lock-variable-name-face ((t (:foreground "#c6c6c6"))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#729fcf"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((((class color) (background light)) (:background "grey95")) (((class color) (background dark)) (:background "#262626")) (t (:background "#767676"))))
 '(header-line ((t (:inherit mode-line :inverse-video nil))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:box nil :foreground "#af87d7" :background "#3a3a3a"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#767676" :background "#303030" :inherit (mode-line)))))
 '(isearch ((t (:foreground "#262626" :background "#d75f5f"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:foreground "#262626" :background "#af87d7"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(show-paren-match ((t (:weight bold :foreground "#d75f5f"))))
 '(default ((t (:inherit nil :stipple nil :background "#262626" :foreground "#c6c6c6" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 136 :width normal)))))

(provide-theme 'photon)
