" =============================================================
" Description:  Main Vim Configuration File
" File:         ~/.vim/vimrc
" =============================================================

" Essentials
set encoding=utf-8
filetype plugin indent on
if !exists('g:syntax_on')
    syntax enable
endif
set hidden
set autoread
set mouse=a
set backspace=indent,eol,start
set spelllang=en_gb
set lazyredraw
set showmatch

" Searching
set ignorecase  " Ignore case in searches
set smartcase   " Enables smart case mode
set hlsearch    " Highlight all search results
set incsearch   " Searches for strings incrementally
set wrapscan    " Wrap back to the start of the file

" Backup, Swap & Undo files
let s:dirs = [expand($HOME.'/.vim/backup'),
            \ expand($HOME.'/.vim/swap'),
            \ expand($HOME.'/.vim/undo')]
for s:dir in s:dirs
    if !isdirectory(s:dir)
        call mkdir(s:dir, 'p')
    endif
endfor
let &backupdir = s:dirs[0]
set backup
let &directory = s:dirs[1]
if has('persistent_undo')
    let &undodir = s:dirs[2]
    set undofile
endif

" Dictionary file
if filereadable('/usr/dict/words')
    set dictionary=/usr/dict/words
elseif filereadable('/usr/share/dict/words')
    set dictionary=/usr/share/dict/words
endif

" Set leader and localleader keys
let mapleader = " "
" let maplocalleader = "\\"
let maplocalleader = " m"

" Vim Omnicomplete, Ins-complete & Wild menu
set omnifunc=syntaxcomplete#Complete
set wildmenu
set wildignore+=*/tmp/*,*.so,*.pyc,*.db,*.sqlite,*/node_modules/*,*/.git/*,*.dll,*.exe,*.cache,*.o
set path+=**

" Indentation config (spaces > tabs)
set tabstop=8
set softtabstop=4
set shiftwidth=4
set expandtab
set shiftround
set autoindent

" Line wrap config (Use soft wrap for code, and hard wrap for comments and text)
let &showbreak='+++ '   " Prefix for soft wrapped line
set textwidth=0         " Maximum width of text
set wrapmargin=0        " Set wrap margin on right of screen
set wrap                " Enable line wrap
set linebreak           " Breaks lines at words
set nolist              " List disables linebreak
if exists('+breakindent')
    set breakindent     " Set wrapped text to visually indent
endif
