[tools]
java = 'temurin-20'
clojure = 'latest'
lein = 'latest'
babashka = 'latest'
clj-kondo = 'latest'
cljfmt = 'latest'

[plugins]
clojure = 'https://github.com/b-social/asdf-clojure'
lein = 'https://github.com/b-social/asdf-lein'
babashka = 'https://github.com/b-social/asdf-babashka'
clj-kondo = 'https://github.com/b-social/asdf-clj-kondo'
cljfmt = 'https://github.com/b-social/asdf-cljfmt'
terraform = 'https://github.com/b-social/asdf-hashicorp'

[settings]
experimental = true
