#!/bin/sh

# Install the following apps:
# - Termux
# - Termux:Styling
# - Termux:API
# - Termux:Widget

# Update the existing packages
apt update
apt upgrade

# Create symbolic links to the user's Android file system
termux-setup-storage

# TODO Set up termux API

apt install stow git vim tmux

git clone https://github.com/axvr/dotfiles --recurse-submodules
