nop %sh{
    mkdir -p "$kak_config/autoload"
    ln -s "$kak_runtime/rc" "$kak_config/autoload/standard-library"
}

colorscheme plain
define-command mkdir %{ nop %sh{ mkdir -p "$(dirname "$kak_buffile")" } }

add-highlighter global/ show-matching

set-option global ui_options terminal_assistant=none
