# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

# Load ~/.Xresources
xrdb ~/.Xresources

# Start window manager on login
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    #exec sway
    #exec startx
    continue
fi

